### ISSUE TITLE
Add Landon Abney to the Linter team

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/Meta#1]
This is where we discuss about the addition of a new member to the family @Arcanemagus (Landon Abney).
He has transitioned `linter-php`, `linter-csslint`, `linter-phpmd` to the latest API and has been active in the org since, he has also been sending PRs to these repos (and others too maybe?).

Please post your opinions below as `:+1:` or `:-1:`.

/cc @AtomLinter/linter @AtomLinter/owners

**Comment by keplersj** [comment]
As well he has been very attentive and active on the Slack channel. For that alone he should be considered part of the family.

:+1:

**Comment by AsaAyers** [comment]
I'm definitely :-1:  on setting up a new repo to vote on members. We need to document who the maintainers of each linter are. While everyone in @AtomLinter/linter has commit access to `linter-coffeelint` I am the one who is maintaining it and making releases.

new members should not be thrown into @AtomLinter/linter, the existing process is to create a group matching the name of the repo and put people there.

Can someone tell me who actually makes releases for `linter-php` `linter-csslint` and `linter-pmd`?

**Comment by keplersj** [comment]
Oh. I didn't realize he'd be added to @AtomLinter/linter. I support adding him to those repos he's worked on as a maintainer.

**Comment by AsaAyers** [comment]
https://github.com/AtomLinter/linter-rubocop/pull/57 is an excellent example of why we don't need this repo or voting on members

**Comment by AsaAyers** [comment]
IMO, the majority of the decision on "Can {person} join linter-{x}" is up to the maintainers of that linter. If no one is currently taking responsibility for that project then we need to step in and grant ownership. That's how I came to be the maintainer of `linter-coffeelint`, it had been abandoned.

**Comment by steelbrain** [comment]
@AsaAyers I agree that we shouldn't be adding new members directly to that team, about those repos, I am the one maintaining them.

**Comment by keplersj** [comment]
I agree with you @AsaAyers. Individual tickets should be opened up on those repos to add him as a contributor/maintainer.

**Comment by steelbrain** [comment]
I grabbed the idea of a separate repo to discuss about the org itself from @nodejs, and I found it to be quite nice, everything meta in one place and bugs and feature requests in other places.

**Comment by AsaAyers** [comment]
I think it would be nice if we could add a standard footer to all of our READMEs explaining who has taken responsibility for each repository. It doesn't look like teams exist for those repos, so later tonight I'll create teams and assign members starting with @steelbrain  and @Arcanemagus 

I'm not 100% against Meta, I just think the individual repos make more sense for this type of item unless we're discussing joining /linter or /owners. But even then, how is this better than slack?

**Comment by keplersj** [comment]
I think meta has it's place, for more formal issues. Adding and removing team members is not worth a public ticket in my opinion.

**Comment by steelbrain** [comment]
@AsaAyers I love the idea of writing maintainers in the README, it makes it easier for people to find out who's maintaining a linter and reach them for queries. and Thanks :wink: 

Also meta has a lot of use cases IMO, we can put the list of abandoned repos here for people to contribute to, and eventually start maintaining it, and I believe it's better than slack because it keeps the history intact, Atom's slack has a limit of 10k messages and deletes everything after that.

@k2b6s9j I just like the idea of having a team meeting every week (or a few weeks) and discussing about the org and talking about the people who have been contributing lately and adding them to org. but because we can't have a meeting every week, a meta repo doesn't hurt IMO.

**Comment by AsaAyers** [comment]
> put the list of abandoned repos here

:+1:

> talking about the people who have been contributing lately and adding them to org

Shouldn't we wait for people to ask be become members? Or is that an implied step here?

**Comment by Arcanemagus** [comment]
Personally I like the approach of approaching people who are already helping out, as it's been my experience managing communities that often the people asking for power are the last ones that should have it :stuck_out_tongue:.

That being said, there are situations where it is perfectly appropriate (especially here where a project may be abandoned with users still using it that deserve help).

I'm happy to help wherever I can :wink:.

**Comment by steelbrain** [comment]
Closing as he's in
