### ISSUE TITLE
Permission to move linter-pug

### ISSUE THREAD

**Issue by matthojo** [AtomLinter/Meta#14]
I have just built https://github.com/matthojo/atom-linter-pug would anyone mind if I moved it to the AtomLinter org?

Moved from: https://github.com/steelbrain/linter/issues/1169

**Comment by Arcanemagus** [comment]
Not at all! The general procedure is outlined [here](https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository), and it might help to be able to chat on [Atom's Slack](http://atom-slack.herokuapp.com/) to speed up the process.

**Comment by Arcanemagus** [comment]
@matthojo Let me know when you want to migrate that over 😉.

**Comment by matthojo** [comment]
@Arcanemagus I've requested a transfer to you.

**Comment by Arcanemagus** [comment]
Transferred, team with write access created that you can invite people to, and you've been given explicit admin access on the repo.

Welcome! 🎉
