### ISSUE TITLE
Add list of unmaintained repos

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/Meta#2]
Just like the title says

**Comment by SpainTrain** [comment]
It would be cool to generate this list procedurally.  One idea is to use something like the "long open issues" metric from http://packagequality.com/#?package=express-appengine-handlers

**Comment by Arcanemagus** [comment]
This wouldn't depend on it being an `npm` package: http://isitmaintained.com/

Ex: http://isitmaintained.com/project/AtomLinter/linter-php

**Comment by SpainTrain** [comment]
OMG THANK YOU!  I just spent about 10 minutes trying to google to find that site!!

**Comment by steelbrain** [comment]
Closing in favor of #10
