### ISSUE TITLE
[meta] making the organization open access for @atom-community 

### ISSUE THREAD

**Issue by aminya** [AtomLinter/Meta#21]
Some of the repositories of this organization such as linter-eslint, have not been active, and there are many [bugs](https://github.com/AtomLinter/linter-eslint/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and [pull requests](https://github.com/AtomLinter/linter-eslint/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) that are left unattended. 

As the head owner of @atom-community, I would like to request @atomlinter to open up access to this organization for the @atom-community members. 

This will give @atomlinter a new life and hopefully fixes the bugs and issues.

If AtomLinter thinks that this organization would be better-closed access, we will fork the whole organization and continue the development.

_PS-1: This issue has been copied to the @atom-community group chat._
_PS-2: Linter-eslint was chosen as a public place that we can make our request._

**Comment by Arcanemagus** [comment]
I haven't had time to dedicate to this org that it needs, since you've consistently shown interest I'll give you owner in the organization 😉.
