### ISSUE TITLE
Moving linter-markdown to AtomLinter org

### ISSUE THREAD

**Issue by leipert** [AtomLinter/Meta#4]
Hey there, i would love to move linter-markdown ([gh](https://github.com/leipert/linter-markdown)/[apm](https://atom.io/packages/linter-markdown)) to the AtomLinter org.

**Comment by keplersj** [comment]
I know that you wanted to transfer in order to get on the "official list." However, since then I have added a ton of community made linters to the official list, in order to encourage more developers, like you, to make linter packages.

I'm not discouraging your transfer, in fact I encourage it if you want to transfer. Just thought that should be brought up.

**Comment by leipert** [comment]
I do not care that much where the package is.

Moving it to @AtomLinter implies the possibility of better quality of the package by code reviews, etc.
So that would be a big pro.

**Comment by AsaAyers** [comment]
I'm not sure if you can initiate the transfer from settings or not. I have invited you to the org, if you're able to start the transfer it would be at the bottom of https://github.com/leipert/linter-markdown/settings

It might require being an admin on both sides. If so, could you make me an owner of your repo and I'll move it?

**Comment by leipert** [comment]
Yeah, I would definitely do that. But what about the atom package? How do i transfer ownership there?

**Comment by AsaAyers** [comment]
@k2b6s9j didn't you move a repo at some point? Do you know how to move the atom package?

**Comment by leipert** [comment]
https://atom.io/docs/latest/behind-atom-maintaining-your-packages

It seems like I just have to move the package.

**Comment by AsaAyers** [comment]
https://github.com/AtomLinter/linter-markdown Success!

Welcome to the team :)

**Comment by leipert** [comment]
Thanks :+1: 

Pushing a new version also succeeded:

![screen shot 2015-09-03 at 14 03 52](https://cloud.githubusercontent.com/assets/2906107/9657831/d59468be-5244-11e5-94aa-c585ea9da759.png)

**Comment by steelbrain** [comment]
@leipert Congratulations :tada:

**Comment by leipert** [comment]
:tada: :balloon: :trophy:
