### ISSUE TITLE
Make @Steelbrain an Owner

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/Meta#5]
He is doing great work with the linter, as well as finding maintainers for abandoned packages.

cc @AtomLinter/owners

**Comment by steelbrain** [comment]
Awww, Thank You :bow:

**Comment by AsaAyers** [comment]
@steelbrain You are now an owner.

**Comment by steelbrain** [comment]
Awesome, Thanks :bow:

**Comment by AsaAyers** [comment]
IDK if it's been documented anywhere, but the process for adding people to repos has been to make a team with the same name as the repo, then add people to the team. Also, don't forget to add the repo to the team.

I have noticed a few teams aren't consistent and manage multiple repos. Most of the recent additions to maintainers have required creating new teams.

**Comment by steelbrain** [comment]
Thanks for the tip.
